#
# Variant calling.
#
# Docs: https://www.biostarhandbook.com/
#

# Primary variables.

# Genome accession from GenBank.
ACC = GCF_000848505.1

# Genome name
NAME= Ebola.Mayinga.1976

# SRR number.
SRR = SRR1972918

# The sample name.
SAMPLE = G5731.1

# Number of reads to download.
N=100000

# Additional variables set below.

# The reference genome.
REF = refs/${NAME}.fa

# The annotation file.
GTF = refs/${NAME}.gtf

# The read pairs.
R1 = reads/${SAMPLE}_1.fq
R2 = reads/${SAMPLE}_2.fq

# The alignment file.
BAM = bam/${SAMPLE}.bam

# The variants with bcftools.
VCF = vcf/${SAMPLE}.vcf.gz

# Number of CPUS
NCPU = 4

# Makefile customizations.
SHELL := bash
.DELETE_ON_ERROR:
.ONESHELL:
.SHELLFLAGS := -eu -o pipefail -c
MAKEFLAGS += --warn-undefined-variables --no-print-directory

usage:
	@echo "#"
	@echo "# Short read variant calling."
	@echo "#"
	@echo "# Input variables."
	@echo "#"
	@echo "# ACC=${ACC}"
	@echo "# NAME=${NAME}"
	@echo "#"
	@echo "# SRR=${SRR}"
	@echo "# SAMPLE=${SAMPLE}"
	@echo "#"
	@echo "# Resulting files:"
	@echo "#"
	@echo "# REF=${REF}"
	@echo "# GTF=${GTF}"
	@echo "# R1=${R1}"
	@echo "# R2=${R2}"
	@echo "# BAM=${BAM}"
	@echo "# VCF=${VCF}"
	@echo "#"
	@echo "# make run|igv|clean"
	@echo "#"

run:
	# Download the reference genome.
	make -f src/run/datasets.mk \
		ACC=${ACC} \
		REF=${REF} \
		GTF=${GTF} \
		fasta gtf

	# Download the short reads.
	make -f src/run/sra.mk \
		SRR=${SRR} \
		N=${N} \
		R1=${R1} \
		R2=${R2} \
		run

	# Index the genome then align the reads to the reference genome.
	make -f src/run/bwa.mk \
		R1=${R1} \
		R2=${R2} \
		REF=${REF} \
		BAM=${BAM} \
		NCPU=${NCPU} \
		index run

	# Call variants with bcftools.
	make -f src/run/bcftools.mk \
		REF=${REF} \
		BAM=${BAM} \
		VCF=${VCF} \
		NCPU=${NCPU} \
		run

# Remove the variant calls generated by the pipeline
run!:
	rm -f ${VCF}

clean:
	rm -f ${R1} ${R2} ${BAM} ${BAM}.* 
	rm -f ${VCF} ${VCF}.*

all: run

# IGV command automation.
NC = nc localhost 60151

igv: run
	echo "new" | ${NC}
	echo "genome $$PWD/${REF}" | ${NC}
	echo "load $$PWD/${GTF}" | ${NC}
	echo "load $$PWD/${VCF}" | ${NC}
	echo "load $$PWD/${BAM}" | ${NC}


.PHONY: usage run run! clean igv all